Algoritmo "Conversor de Moedas(Dolar)"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Professor   : Gustavo Guanabara
// Descrição   : Converte Reais em Dólar
// Autor(a)    : Fernanda Maresi
// Data atual  : 11/02/20
Var
// Seção de Declarações das variáveis 
  dolares:real
  reais:real
  

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Quantos reais eu tenho? ")
 leia (reais)
 dolares <- reais / 2.22
 Escreval ("Eu tenho ",dolares)

Fimalgoritmo