Algoritmo "Cont10"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Conta até 10 com o laço Para.
// Autor(a)    : Fernanda Maresi
// Data atual  : 18/02/20
Var
// Seção de Declarações das variáveis 
cont:inteiro

Procedimento Cont10(C:inteiro)
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Para C <- 1 ate 10 passo 1 faca
       Escreval(C)
    Fimpara
    
FimProcedimento

Inicio

Cont10(cont)

Fimalgoritmo