
Algoritmo "Contador-Ate10"
// Disciplina  :  [Linguagem e Lógica de Programação]
// Professor   : Gustavo Guanabara
// Descrição   : Conta até 10 com o laço Para
// Autor(a)    : Fernanda Maresi
// Data atual  : 11/02/20

Var
// Seção de Declarações das variáveis 
cont:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
    Para cont <- 1 ate 10 passo 1 faca
       Escreval(cont)
    Fimpara

Fimalgoritmo