Algoritmo "Olá, Mundo"
// Disciplina  :  [Linguagem e Lógica de Programação] 
// Descrição   : Imprime a mensagem
// Autor(a)    : Fernanda Maresi
// Data atual  : 31/10/2018
Var
// Seção de Declarações das variáveis 
 msg: caractere

Inicio
    // Seção de Comandos, procedimento, funções, operadores, etc... 
    msg <- "Olá Mundo!"
    Escreval("Mensagem ", msg)
    Escreva("Primeiro, programa")
Fimalgoritmo
