algoritmo "semnome"
// Função :
// Autor :
// Data : 08/08/2017
// Seção de Declarações 
var
A,B,C:inteiro
inicio
A <- 2
B <- 3
C <- 5

escreval(A>B)
escreval(a = b)
escreval(A <> B)
ESCREVAL(A > 2)
ESCREVAL(A >= 2)
ESCREVAL(C = A+B)
ESCREVAL(C >= B ^ A)
ESCREVAL(C <= B ^ A)
escreval("  ")
escreval("  ")
ESCREVAL(B <= C % A)
ESCREVAL(B <= C % 2)
ESCREVAL(1 = C % 2)



// Seção de Comandos 
fimalgoritmo
